#!/usr/bin/python

import sys
import time
import serial
print serial.VERSION

import rospy
from std_msgs.msg import Float32

# Open serial port
print "Sensor uart initialisation...",
sys.stdout.flush()
ser = serial.Serial('/dev/ttyACM0', 9600)
ser.close()
ser.setParity('N')
ser.setStopbits(1)
ser.setTimeout(0)
ser.open()
time.sleep(1.0)
print "[ok]"

# Set Led State
byte_data = [0xAA, 200, 10]
ser.write(''.join(chr(x) for x in byte_data))

# Init ros node
rospy.init_node('payload_monitor', anonymous=True)
pub = rospy.Publisher('status/payload_battery', Float32, queue_size=1)
rate = rospy.Rate(1) # 1hz

while not rospy.is_shutdown():
                msg = ser.readline()	
		volt = float(msg)
            	print("PC voltage = {0:.3f}".format(volt))
            	pub.publish(volt)
		rate.sleep()                

            
byte_data = [0xAA, 200, 100]
ser.write(''.join(chr(x) for x in byte_data))
print("byby")

