#!/usr/bin/env python
import rospy
from std_msgs.msg import String

def watchdog():
    pub = rospy.Publisher('status/watchdog', String, queue_size=1)
    rospy.init_node('watchdog_node') #, anonymous=True)
    rate = rospy.Rate(1) # 10hz
    while not rospy.is_shutdown():
        pub.publish("alive")
        rate.sleep()

if __name__ == '__main__':
    try:
      	watchdog()
    except rospy.ROSInterruptException:
        pass
